[workspace]
members = [
	"address",
	"anonima",
	"crypto",
	"db",
	"encoding",
	"key_management",
	"message",
	"network",
    "utils/bigint",
    "utils/bitfield",
    "utils/hash_utils",
    "utils/json_utils",
    "utils/net_utils",
]
