condense_wildcard_suffixes = true
format_code_in_doc_comments = true
max_width = 100
hard_tabs = false
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
